inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
require: rubocop-rspec
AllCops:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'config.ru'
    - 'Gemfile'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/rails_helper\.rb'
    - 'spec/spec_helper\.rb'
    - 'app/mailers/**/*'
    - 'app/jobs/**/*'
    - 'node_modules/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*'
    - 'spec/views/**/*'
    - 'spec/lint/rubocop_spec\.rb'

Documentation:
  Enabled: false

# skips style of child classes and modules.
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_examples']
